### ISSUE TITLE
Close tab button: UI glitch on Tabs Toolbar

### ISSUE THREAD

**Issue by Gittyperson** [stux2000/Tab_Utilities_Phoenix#1]
Small glitch when moving the mouse over different tabs. Toggling the following two options doesn't make a difference. Small video attached.

- Mouse click (down and release) to focus a tab
- Mouse hover to focus a tab with a delay of x ms

Problem appears when these two are enabled:

Appearance/Tab Bar/Show on tab bar/[Close Tab] button:

- on pointed tab only
- on active/pointed tab

Win 10 Pro x64, Pale Moon 28.0.0a4 (PM 27 is ok)

[UI glitch.zip](https://github.com/stux2000/Tab_Utilities_Phoenix/files/2091977/UI.glitch.zip)

**Comment by stux2000** [comment]
Hmmm. Thanks for letting me know that this is still an issue! (And that 28.0.0a4 is out!)  I saw this on a2 when nothing was working and I don't see it now on a4.  I'll re-test on a clean profile as likely I have settings that hide those close buttons (there's several "little" things that still aren't working either, such as the tab groups notch to expand/contract).

**Comment by JustOff** [comment]
This is a known issue: [[PALEMOON] Win8+ close icons incorrectly mapped](https://github.com/MoonchildProductions/UXP/issues/317).

**Comment by Gittyperson** [comment]
Ok thanks, I'll close this then.
