### ISSUE TITLE
Version 28.11.0 broke "Open new tabs next to current tab"

### ISSUE THREAD

**Issue by letmeindude** [stux2000/Tab_Utilities_Phoenix#10]
After installing 28.11.0 open new tabs next to current tab doesn't work anymore.
Maybe it has something to do with the new pref _browser.tabs.insertAllAfterCurrent_, but it is disabled by default, so...

EDIT: I'm not sure about this, because I'm using Mypal - fork of Pale Moon, so I'm going to close this issue for now.

**Comment by stux2000** [comment]
Thanks for bringing this up! 

Issue #8  should cover this I think. I wouldn't be surprised if the issue you reported is also found in mainstream PM.  I just haven't had much time to devote to testing much less debugging this issue.

P.S. I'd never heard of MyPal before, although the website doesn't have much information on how it differentiates itself from PM.
